### ISSUE TITLE
Does this work on Windows?

### ISSUE THREAD

**Issue by CleanCut** [CleanCut/headtail#21]
It would be good if someone (not me 😆) would figure out if this utility works on Windows, and if not -- can we make it work without too much trouble?

**Comment by CleanCut** [comment]
I tried enabling CI for windows, and [3 of 8 tests failed](https://github.com/CleanCut/headtail/actions/runs/3101478853/jobs/5022881671).

I don't know whether it's a problem with the tests, with headtail itself, or both. But it seems feasible that someone with Windows could get this working.

**Comment by tbmreza** [comment]
I can't reproduce what the CI is getting.
```
     Running tests\integration.rs (target\debug\deps\integration-8b71928931c7

running 8 tests
test head ... ok
test help ... ok
test argless ... ok
test head_length_exceeds_file_length ... ok
test overlapping_head_and_tail ... ok
test tail ... ok
test tail_length_exceeds_file_length ... ok
test follow_detects_recreation ... ok

test result: ok. 8 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.19s
```

I think I know where the failure is coming from. Windows treats line endings differently by default. https://stackoverflow.com/a/20653073
Pull request (trying this https://github.com/actions/checkout/issues/135#issuecomment-602171132) coming right up.
